Feature/grow 262
Team-Planz/Planz-iOS pull request #11
Opened 2023-01-15 07:53 UTC by escapeanaemia

## ISSUE
- resolved #{issue_number}

<br>

## 작업 내용
- 작업 범위를 작성해 주세요

<br>

## 실행 화면

| Screen Shot | Screen Shot |
| ----------- | ----------- |
|             |             |

<br>

## Check List
- [ ] PR 제목은 `[ISSUE-{N}] PR 제목`으로 작성
- [ ] CI/CD 통과 여부
- [ ] 1명 이상의 Approve 확인 후 Merge
- [ ] 관련 이슈 연결

2023-02-08 08:23 UTC, junyng reviewed
기존 개발 환경과 달라서 어려움이 있으셨을텐데
`SwiftUI`, `ComposableArchitecture`를 
적용하시느라 고생많으셨습니다 !
몇가지 코맨트 남겨놓았습니다 감사합니다

2023-02-08 08:23 UTC, junyng commented on AppPackage/Sources/MakePromise/SubViews/TopInformationView.swift
> +                        Text("/ 5").foregroundColor(PDS.COLOR.gray3.scale)
현재 작성해주신 단계는 1,2 단계이나
전체 스텝의 갯수는 변경될 수 있는 값으로 보입니다
`viewStore.steps.count` 등의 정보를 추가하는 것이 어떨까요?

2023-02-08 08:23 UTC, junyng commented on AppPackage/Sources/MakePromise/MakePromiseStore.swift
> +}
약속을 잡는 과정에 대한 `State`들이 포함되어 이해하기 수월하였습니다
현재는 '테마 선택', '장소 선택'에 대한 과정이 포함되어 있지만 
화면 순서가 변경될 여지, 추후 추가될 수 있는 '달력 선택', '시간 범위 선택', '시간 선택'을 고려하여 
array 형태로 `Step`을 관리하는것이 어떨까요?

코드 예시는 다음과 같습니다
```
var steps: [Step]

enum Step: Equatable {
  case selectTheme(SelectThemeState)
  case setNameAndPlace(SetNameAndPlaceState)
  case ...
}
```

``` use cases
let state = MakePromiseState(steps: [.selectTheme(.init()), .setNameAndPlace(.init()),...])
```

2023-02-08 08:57 UTC, GangWoon requested changes
처음 TCA 아키텍쳐를 도입하시느냐 고생 많으셨습니다 :)
구현을 하실 때, 뷰에다가 상태값을 생성하시는 곳이 몇곳 존재했습니다.
이를 Store 내부 상태로 이동시켜서 리듀서에서 사용되는 값과 싱크를 맞추셨으면 좋겠습니다.

2023-02-08 08:57 UTC, GangWoon commented on AppPackage/Sources/MakePromise/MakePromise.swift
> +    let store: Store<MakePromiseState, MakePromiseAction> = Store(
스토어를 해당 뷰에서 생성할 필요는 없을 거 같습니다.

2023-02-08 08:57 UTC, GangWoon commented on AppPackage/Sources/MakePromise/MakePromise.swift
> +                    Spacer()
공백의 위치를 에러 뷰 내부로 옮기시는 건 어떤가요?

2023-02-08 08:57 UTC, GangWoon commented on AppPackage/Sources/MakePromise/MakePromise.swift
> +    @State private var promiseStep: MakePromiseStep = .selectTheme
해당 프로퍼트를 생성하신 이유가 있을까요?

2023-02-08 08:57 UTC, GangWoon commented on AppPackage/Sources/MakePromise/SubViews/MakePromiseBottomButton.swift
> +                    PromiseNextButton(store: store)
Button 컴포넌트를 사용하지 않고 제스처를 추가 시킨 이유가 있으실까요?

2023-02-08 08:57 UTC, GangWoon commented on AppPackage/Sources/MakePromise/SubViews/SelectThemeView.swift
> +                .padding(listItemEdgePadding)
PromiseType이 CaseIterable를 채택했기 때문에 아래와 같이 코드를 축약시킬 수도 있을 거 같습니다.
ForEach(PromiseType.allCases, id: \.self) {
    SelectThemeItemView(promiseType: $0, store: store)
}
또한 SelectThemeItemView에서 store로 엑션을 전달하는 과정에서 자기 타입을 집어넣어서 전달하는 방식 보단,
외부에서 스코핑을 해주는 방식이 된다면 타입을 집어넣지 않고도 가능해 보입니다.

2023-02-08 08:57 UTC, GangWoon commented on AppPackage/Sources/MakePromise/SubViews/SelectThemeView.swift
> +    var store: Store<SelectThemeState, SelectThemeAction>
뷰 상태값을 꼭 필요로 하지 않는 이상 두지 않으셨으면 좋겠습니다.
해당 부분에 대해서 어떻게 생각하시나요?

2023-02-08 08:57 UTC, GangWoon commented on AppPackage/Sources/MakePromise/SubViews/SetNameAndPlaceStore.swift
> +        state.promisePlace = place
글자 수 제한에 관한 처리가 누락된 거 같습니다.

2023-02-08 08:57 UTC, GangWoon commented on AppPackage/Sources/MakePromise/SubViews/SetNameAndPlaceView.swift
> +    @State var textFieldText = ""
뷰 상태값을 따로 두지 않았으면 한다는 코맨트와 동일합니다.

2023-02-08 08:57 UTC, GangWoon commented on AppPackage/Sources/MakePromise/SubViews/SetNameAndPlaceView.swift
> +            TextFieldWithTitleView(titleText: "장소(선택)", placeHolderText: "강남, 온라인 등")
String literal이 아닌, 타입으로 관리하시는 방법은 어떠신가요??
PromiseType처럼 관리하는 방식이 휴먼 에러를 방지하기 더 적합해 보여서 질문드립니다.

2023-02-08 08:57 UTC, GangWoon commented on AppPackage/Sources/MakePromise/SubViews/TopInformationView.swift
> +                            .foregroundColor(Color(hex: "3E414B"))
해당 부분 컬러값을 직접 사용하고 있습니다.

2023-02-08 08:57 UTC, GangWoon commented on AppPackage/Sources/MakePromise/SubViews/MakePromiseBottomButton.swift
> +public struct PromiseNextButton: View {
하나의 뷰 컴포넌트로 나누시려면 엑션을 스코핑하거나 아니면 상위 뷰에서 프로퍼티로 분리시키시는 건 어떠신가요?

2023-02-08 09:02 UTC, GangWoon commented on AppPackage/Sources/MakePromise/MakePromiseStore.swift
> +}
다른 데이터 타입에 대해서 순서 정해져 있으니 enum 타입으로 명시하며 연관 값을 채택하게 되니까 이해하기 더 수월해 보입니다 :)
저도 준영님 의견이 좋은 거 같아요.

2023-02-12 10:59 UTC, escapeanaemia commented on AppPackage/Sources/MakePromise/MakePromise.swift
> +                }
aa4ad11f1d88a0c6292eb121b775e988a812cb6d

2023-02-12 11:05 UTC, escapeanaemia commented on AppPackage/Sources/MakePromise/SubViews/SelectThemeView.swift
> +                .padding(listItemEdgePadding)
SwiftUI에서 forEach 로 어떻게 뷰를 그리는지 궁금했는데 저렇게 하면 되는군요 허허

2023-02-12 11:05 UTC, escapeanaemia commented on AppPackage/Sources/MakePromise/SubViews/SelectThemeView.swift
> +                .padding(listItemEdgePadding)
> 외부에서 스코핑을 해주는 방식이 된다면 타입을 집어넣지 않고도 가능해 보입니다.

어떤 말인지 이해가 안되는데 좀 더 설명해주실 수 있나요?

2023-02-12 11:12 UTC, escapeanaemia commented on AppPackage/Sources/MakePromise/SubViews/SetNameAndPlaceView.swift
> +            TextFieldWithTitleView(titleText: "장소(선택)", placeHolderText: "강남, 온라인 등")
56aae4871e4473f55611b4935b19e2de9b5a4ac4

2023-02-12 11:13 UTC, escapeanaemia commented on AppPackage/Sources/MakePromise/SubViews/TopInformationView.swift
> +    let xmark = "xmark"
상수만 관리하는 모듈하나 만들까요?

2023-02-14 02:35 UTC, GangWoon commented on AppPackage/Sources/MakePromise/SubViews/SelectThemeView.swift
> +                .padding(listItemEdgePadding)
```swift
/// MARK: - VStack Container
///
struct A: ReducerProtocol {
    struct State: Equatable {
        var selectedType: PromiseType? {
            itemList
                .first { $0.isSelected }
                .map { $0.promiseType }
        }
        var itemList: IdentifiedArrayOf<B.State> = []
    }
    
    enum Action: Equatable {
        case onAppear
        case comparedSelectThemeItemViewAction(id: B.State.ID, action: B.Action)
    }
    
    @Dependency(\.uuid) var uuid
    
    func reduce(
        into state: inout State,
        action: Action
    ) -> EffectTask<Action> {
        switch action {
        case .onAppear:
            let list = PromiseType.allCases
                .map { B.State(id: uuid(), promiseType: $0) }
            state.itemList.append(contentsOf: list)
            
            return .none
            
        case let .comparedSelectThemeItemViewAction(id, .buttonTapped):
            state.itemList[id: id]?.isSelected.toggle()
            return .none
        }
    }
}

struct AView: View {
    var store: StoreOf<A>
    let listItemEdgePadding = EdgeInsets(top: 6, leading: 20, bottom: 6, trailing: 20)
    
    var body: some View {
            VStack(){
                Spacer()
                ForEachStore(
                    store
                        .scope(
                            state: \.itemList,
                            action: A.Action.comparedSelectThemeItemViewAction(id:action:)
                        ),
                    content: BView.init
                )
                Spacer()
            }
            .background(Color.white)
    }
}


/// MARK: - Row
struct B: ReducerProtocol {
    struct State: Equatable, Identifiable {
        var id: UUID
        var isSelected: Bool = false
        let promiseType: PromiseType
    }
    
    enum Action: Equatable {
        case buttonTapped
    }
    
    func reduce(
        into state: inout State,
        action: Action
    ) -> ComposableArchitecture.EffectTask<Action> {
        return .none
    }
}

struct BView: View {
    let store: StoreOf<B>
    let viewStore: ViewStoreOf<B>
    let itemCornerRadius: CGFloat = 16
    let checkMarkCircle = "checkmark.circle"
    let checkmarkCircleFill = "checkmark.circle.fill"
    
    init(store: StoreOf<B>) {
        self.store = store
        self.viewStore = ViewStore(store)
    }
    
    var body: some View {
            HStack{
                Text(viewStore.promiseType.withEmoji)
                    .foregroundColor(
                        viewStore.isSelected
                        ? Purple._900.scale
                        : Gray._500.scale
                    )
                Spacer()
                Image(
                    systemName: viewStore.isSelected
                    ? checkmarkCircleFill
                    : checkMarkCircle
                )
                    .foregroundColor(
                        viewStore.isSelected
                        ? Purple._900.scale
                        : Gray._500.scale
                    )
            }
            .padding(EdgeInsets(top: 16, leading: 20, bottom: 16, trailing: 20))
            .background(
                viewStore.isSelected
                ? Purple._900.scale.opacity(0.15)
                : Gray._100.scale
            )
            .cornerRadius(itemCornerRadius)
            .overlay(
                RoundedRectangle(cornerRadius: itemCornerRadius)
                    .stroke(
                        Purple._900.scale,
                        lineWidth: viewStore.isSelected ? 0.7 : 0)
            )
            .onTapGesture {
                viewStore.send(.buttonTapped)
            }
    }
}

```

2023-02-14 09:19 UTC, junyng commented on AppPackage/Sources/MakePromise/SubViews/TopInformationView.swift
> +    let xmark = "xmark"
괜찮을것 같습니다..
폰트나, 이미지 정보는 `DesignSystem` 모듈에서 관리하고
localize string 정보는 따로 관리하는것이 어떨까요?

@GangWoon 님도 의견주시면 감사하겠습니다

2023-02-18 06:31 UTC, junyng commented on AppPackage/Sources/MakePromise/MakePromiseStore.swift
> +}
상준님과 페어프로그래밍을 하는 과정에서
각각 다른 서브 액션을 scope 해주는 부분이 어려워서 
이 부분은 다음 스텝에서 진행하도록 하겠습니다
저도 고민해보고 피드백드리도록 하겠습니다 !

2023-02-19 03:09 UTC, GangWoon commented on AppPackage/Sources/MakePromise/SubViews/TopInformationView.swift
> +    let xmark = "xmark"
저도 같은 생각입니다 :)

2023-02-19 03:40 UTC, GangWoon commented
준영님과 어제 고민하셨던 내용을 확인했습니다.
저희가 의견 전달한대로 구현할 수 있는 방법을 찾았습니다. 다만 이를 말로 설명드리고 고치는 작업을 진행하시는 게 좋을 지,
아니면 우선 피알 먼저 머지시키고 제가 수정한 코드를 보면서 학습을 하시는 게 빠를지 질문드리고 싶었습니다.
상준님 의견을 전적으로 반영할 것이기 때문에 편하게 말씀해주시면 좋겠습니다 :)

2023-02-25 06:17 UTC, GangWoon approved these changes

2023-02-25 06:21 UTC, merged