[PI-3] 약속 상세화면 UI 구현과 연결
Team-Planz/Planz-iOS pull request #30
Opened 2023-03-07 11:37 UTC by Jinsujin

## ISSUE
- [#[PI-3]](https://planz-growth.atlassian.net/browse/PI-3)

<br>

## 작업 내용
- [x] 약속관리 모듈 분리
- [x] 약속 상세화면 UI 구현
- [x] 리스트화면에서 셀을 탭했을때 상세화면 이동

<br>

## 실행 화면
![약속상세화면-전환](https://user-images.githubusercontent.com/12508578/223411319-f9e9dd01-43df-454a-a6c9-371995da8863.gif)

<br>

## Check List
- [x] PR 제목은 `[ISSUE-{N}] PR 제목`으로 작성
- [x] CI/CD 통과 여부
- [ ] 1명 이상의 Approve 확인 후 Merge
- [x] 관련 이슈 연결

2023-03-08 01:03 UTC, GangWoon requested changes
Lint가 적용되는 커밋을 따로 빼주셨으면 좋겠습니다 :)
처음 커밋에 린트가 포함되어 있어서 코드 체인지를 확인하기 어려웠습니다.
고생 많으셨습니다.

2023-03-08 01:03 UTC, GangWoon commented on AppPackage/Sources/PromiseManagement/ConfirmedDetail/ConfirmedDetailView.swift
> +                    .frame(width: 340, alignment: .leading)
고정된 값을 사용하셨을 때, 여러 기기에서 확인해보셨을 까요?
Max 시리즈와, 작은 화면에서의 결과 값이 궁금합니다.

2023-03-08 01:03 UTC, GangWoon commented on AppPackage/Sources/PromiseManagement/HeaderTab/HeaderTabView.swift
> +        buttonLeadings = [0, barWidth + spacing]
버튼 리딩값이 다르게 적용되어서 배열로 관리를 하셨던걸까요?
어디에 사용되는지 확인할 수 없기에 0, someValue는 처음 보는 사람에게 많은 어려움을 주는 거 같습니다.

2023-03-09 06:39 UTC, Jinsujin commented on AppPackage/Sources/PromiseManagement/Confirmed/ConfirmedCellView.swift
> +        /// 약속명
옙 알겠습니다!

2023-03-09 06:40 UTC, Jinsujin commented on AppPackage/Sources/PromiseManagement/Confirmed/ConfirmedListView.swift
> +extension IdentifiedArray where ID == ConfirmedCell.State.ID, Element == ConfirmedCell.State {
더미데이터라 제한해도 괜찮겠군요 알겠습니다!

2023-03-09 06:52 UTC, Jinsujin commented on AppPackage/Sources/PromiseManagement/ConfirmedDetail/ConfirmedDetailView.swift
> +                    .frame(width: 340, alignment: .leading)
고정값으로 화면을 그렸는데, 확실히 이부분은 수정이 필요합니다
1. 디바이스 전체 사이즈에 비례해 컨텐츠 frame width 그리기
2. 일러스트 이미지 크기값을 찾아와 offset 조정
크게 2가지 이슈가 있습니다 수정할께요 🫡

2023-03-09 06:54 UTC, Jinsujin commented on AppPackage/Sources/PromiseManagement/HeaderTab/HeaderTabView.swift
> +        buttonLeadings = [0, barWidth + spacing]
Bar 애니메이션에 필요한 배열값입니다. 조금 더 명확하게 읽혀질 수 있도록 수정할께요!

2023-03-09 06:57 UTC, Jinsujin commented on AppPackage/Sources/PromiseManagement/ConfirmedDetail/ConfirmedDetailView.swift
> +    let store: Store<ConfirmedCell.State, ConfirmedDetailFeature.Action>
아하 그렇게 생각할 수도 있겠군요! 수정하겠습니다!

2023-03-09 07:32 UTC, Jinsujin commented on AppPackage/Sources/PromiseManagement/ConfirmedDetail/ConfirmedDetailView.swift
> +            title = cellState.title
## 리뷰 반영
리스트 화면에서 셀을 터치했을때, 인자로 받아서 상세화면의 State 를 초기화 하도록 했어요.
상위에서 사용하는 객체(ConfirmedCell.State)에 대해 의존성이 생기는데 더 좋은방법이 없을까요?

2023-03-10 01:10 UTC, GangWoon approved these changes
최신 메인 커밋으로 리베이스 후 머지 부탁드리겠습니다 :)

2023-03-11 02:50 UTC, escapeanaemia approved these changes
고생하셨습니다~~!

2023-03-11 02:50 UTC, escapeanaemia commented on AppPackage/Sources/PromiseManagement/ConfirmedDetail/ConfirmedDetailView.swift
> +    private let closeImage = "iconClose"
Image는 View이기 때문에 아래 처럼 변경해도 좋을것 같아요 (마이너한 의견)
```suggestion
    private let illustImageName = "illustDetail"
    private let closeImageName = "iconClose"
```

2023-03-11 02:56 UTC, junyng commented on AppPackage/Sources/PromiseManagement/ConfirmedDetail/ConfirmedDetailView.swift
> +    let store: Store<ConfirmedCell.State, ConfirmedDetailFeature.Action>
참고로 `StoreOf`를 사용하시면 조금 더 간략하게 사용이 가능합니다~!
before
```
    let store: Store<ConfirmedCell.State, ConfirmedDetailFeature.Action>
```
after 
```
    let store: StoreOf<ConfirmedCell>
```

2023-03-11 03:05 UTC, junyng commented on AppPackage/Sources/PromiseManagement/ConfirmedDetail/ConfirmedDetailView.swift
> +                    .frame(width: 340, alignment: .leading)
`GeometryReader`를 사용하여 뷰의 사이즈 정보를 가져올 수 있습니다
example)

```
GeometryReader { proxy in
DetailView()
    .(frame: proxy.size.width *0.6)
}
```

2023-03-11 03:29 UTC, junyng commented on AppPackage/Sources/PromiseManagement/ConfirmedDetail/ConfirmedDetailView.swift
> +            title = cellState.title
`State`를 주입받지 않고 제네릭으로 `View` 를 주입할 수 있는 형태로 바뀌면 좋을것 같습니다
 
```
struct ConfirmedDetailView<Content>: View where Content: View {
    public var body: some View {
        self.content()
    }
}
```
```

2023-03-13 06:39 UTC, Jinsujin commented on AppPackage/Sources/PromiseManagement/ConfirmedDetail/ConfirmedDetailView.swift
> +    private let closeImage = "iconClose"
확실히 뷰라고 인식할 수도 있겠다는 생각이 드네요!  반영하겠습니다!

2023-03-13 07:44 UTC, Jinsujin commented on AppPackage/Sources/PromiseManagement/ConfirmedDetail/ConfirmedDetailView.swift
> +                    .frame(width: 340, alignment: .leading)
GeometryReader 로 비율값으로 frame 사이즈를 정하도록 수정했습니다 

|SE (3세대)|14|14Max Pro|
|-|-|-|
|<img width="226" alt="iphone-SE(3)" src="https://user-images.githubusercontent.com/12508578/224637441-31b3e4aa-c9e1-4605-a630-3722c4c48393.png">|<img width="223" alt="iphone14" src="https://user-images.githubusercontent.com/12508578/224637486-a05490a2-92b4-446a-8f7d-3a4f9c479261.png">|<img width="238" alt="iphone14-promax" src="https://user-images.githubusercontent.com/12508578/224637626-e7cf9705-0c30-4791-b857-3a041288e466.png">|

2023-03-13 07:46 UTC, Jinsujin commented on AppPackage/Sources/PromiseManagement/HeaderTab/HeaderTabView.swift
> +        startXPointForButtons = xPoints
## 리뷰반영
button 이 시작하는 x 좌표라는 것을 분명히 하기 위해 수정했습니다

2023-03-13 08:18 UTC, merged