[ISSUE-PI8] 홈뷰 제작
Team-Planz/Planz-iOS pull request #31
Opened 2023-03-10 02:25 UTC by GangWoon

## ISSUE
- resolved #[PI-8](https://planz-growth.atlassian.net/jira/software/projects/PI/boards/1/backlog?selectedIssue=PI-8)

<br>

## 작업 내용
앱의 뼈대가 될 홈뷰를 제작했습니다.
제작을 하는 과정에서, 데이터로 화면의 진행상황을 표시하려고 노력했습니다.
예를 들어서 상태값을 생성할 때, State(destination: .makePromise(.step1(.식사, .step2(String?, String?)))으로 표시하는 걸 뜻합니다.
enum으로 상태 값을 관리하는 거와, Bool으로 상태 값을 관리하는 것의 차이점은 강제성이라고 생각합니다.
하나의 화면에서 다른 화면을 푸시하거나 모달로 띄우는 상황이 생길 떄, 해당 모델 도메인에 대한 지식을 갖고 있는 사람은 이를 주의하면서 작성하겠지만, 처음 보는 사람의 경우 어떤 방식으로 사용해야할 지 모를 수 있습니다.
이를 Destination이란 열거형으로 함축시켜서 화면의 전환 이동의 경우 해당 enum 값을 사용해서 바인딩했으면 좋겠습니다. 
현재 바인딩하는 과정에서 상태값을 처음 생성할 때, 생성자에서 번거로운 작업을 해야하지만, 추후 TCA 공식 Navigation 라이브러리가 나오면 채택하는 방향으로 가고 싶습니다.

아래 코드를 예시로, 홈 화면에서 makePromise화면을 띄우는 코드입니다.
```
    struct HomeView_Previews: PreviewProvider {
        static var previews: some View {
            HomeView(
                store: .init(
                    initialState: .init(
                        destination: .makePromise(.init())
                    ),
                    reducer: HomeCore()
                )
            )
        }
    }
```

<br>

## 실행 화면

| Screen Shot | Screen Shot |
| ----------- | ----------- |
![Simulator Screen Shot - iPhone 14 - 2023-03-10 at 11 25 09](https://user-images.githubusercontent.com/48466830/224207408-d7115e3d-e8d4-481d-b47c-43b3921ccc30.png)

<br>

## Check List
- [ ] PR 제목은 `[ISSUE-{N}] PR 제목`으로 작성
- [ ] CI/CD 통과 여부
- [ ] 1명 이상의 Approve 확인 후 Merge
- [ ] 관련 이슈 연결

2023-03-11 02:46 UTC, escapeanaemia commented on Planz.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
요건 어떤 이유로 변경된건가요?! 🙂

2023-03-11 02:46 UTC, escapeanaemia commented on AppPackage/Sources/MakePromise/SubViews/TopInformationView.swift
> +                        viewStore.send(.dismiss)
🫶🏼

2023-03-13 02:12 UTC, GangWoon commented on Planz.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
아 제가 의도치 않는 수정을 푸시한 듯 합니다.
해당 코드는 어떻게 수정할 수 있는지 아시나요? 
그리고 꼼꼼하게 봐주셔서 감사합니다 :)

2023-03-13 08:14 UTC, Jinsujin commented on AppPackage/Sources/HomeFeature/HomeView.swift
> +}
오... extension 으로 구현하니까 이미지이름을 뭘로 사용했는지 외부에서 알수 없어서 좋네요!

2023-03-13 08:17 UTC, Jinsujin commented on AppPackage/Sources/HomeConatinerFeature/CasePathHelper.swift
> +}
CasePath 를 어떤식으로 사용하셨는지 설명을 부탁드려도 괜찮을까요?

2023-03-14 17:11 UTC, junyng requested changes
`destinationState` 사용법에 대해 참고할 수 있을것 같아요 수고하셨습니다 🙇‍♂️
몇가지 리뷰 남겼습니다 확인부탁드려요~

2023-03-15 01:35 UTC, GangWoon commented on Planz/AppView.swift
> +        }
테스트 코드가 포함시켰던 거 같습니다. 추후 AppView 자체를 모듈로 분리시킬 거기 때문에
해당 코드를 전부 제거하도록 하겠습니다 :)

2023-03-15 01:40 UTC, GangWoon commented on AppPackage/Sources/HomeConatinerFeature/CasePathHelper.swift
> +}
``` swift
(\HomeContainerCore.State.destinationState)
                 .appending(path: /HomeContainerCore.DestinationState.makePromise)
                 .extract(from:)
```

기존의 존재하는 CasePath에서는 OptionalCasePath를 지원하지 않기에, isoword에서 커스텀으로 사용하시는 코드를 가져왔습니다.
위에 추가한 코드를 예시로 설명드리자면,
WritableKeyPath로 해당 프로퍼티에 접근해서 CasePath를 추가하는 사례입니다.
CasePath<Root, Value>는 enum case의 특정 값을 추출하기 위한 문법이라고 생각하시면 됩니다.
HomeContainerCore.DestinationState enum 중에서 makePromise case만 필터링한다고 이해하시면 될 거 같습니다.

2023-03-15 02:34 UTC, junyng approved these changes

2023-03-15 02:36 UTC, GangWoon commented on Planz.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
해당 코드로 인한 영향이 적어 보여서 머지 후, 방법을 알려주신다면 제거하도록 하겠습니다 :)

2023-03-15 02:36 UTC, merged

2023-03-17 06:39 UTC, junyng commented on Planz.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
Fork에서 amend -> 변경사항 제가하시면 될듯합니다