GROW-320 Create Calendar Client
Team-Planz/Planz-iOS pull request #4
Opened 2022-10-10 07:33 UTC by GangWoon

달력일을 계산할 수 있는 객체를 생성했습니다.
특정 Date를 기준으로 Date가 속한 연도 일을 계산해서, Optional<이전 달 일>, 이번 달 일, Optional<다음 달 일> 을 계산하도록 구현했습니다.
리턴 값은 [[Day]] 2차원 배열입니다. 캘린더 뷰에서 제어할 객체는 [[[Day]]] 3차원 배열입니다.
이를 현재 상황에선 3차원 배열로 표기하지만, 추후에 다른 객체 타입을 생성해서 관리하는 게 용이해 보입니다.

이전에 준영님께 말씀 드렸다 싶이 저희 앱 특성상 Day라는 이름이 여러곳에서 사용될 가능성이 많아 보입니다. 저희가 모듈을 분리시키면서 해당 문제에 대해서 표면적으로 노출되는 건 없지만, 다 같이 생각을 해보는 시간을 갖을 수 있다면 좋을 거 같습니다.

2022-10-11 09:37 UTC, junyng commented
Package.swift 파일에 Target이 등록되어 있지 않은것 같습니다 확인부탁드려요~ 

```
    products: [
        .library(
            name: "AppPackage",
            targets: ["AppPackage", "Calendar"]),
    ],
   ...,
   targets: [
   ...
           .target(
            name: "Calendar"
        )
    ]
```

2022-10-11 13:13 UTC, GangWoon commented
10월 x일 기준으로 createMonth함수를 호출했을 때,  아래와 같은 결과 값을 갖습니다.
이는 원하는 결과 값과 동일한 상태입니다. 테스트 코드는 추후에 작성하도록 하겠습니다.
/// 9         10       11
[25 ... 30, 1 ...31, 1 ... 5]

2022-10-11 23:52 UTC, junyng requested changes

2022-10-11 23:52 UTC, junyng commented on AppPackage/Sources/Calendar/Day.swift
> +    public var isSelectedDate: Bool
Day가 선택되었는지 여부를 알 수 있는 값이므로
Day.isSelected가 어떨까요?

2022-10-11 23:52 UTC, junyng commented on AppPackage/Sources/Calendar/CalendarClient.swift
> +            number: _numberOfDay(date),
Day 타입에 number라는 값을 저장하신 이유가 궁금합니다
DateFormatter를 사용해서 Date의 날짜 정보만 가져와도 괜찮지 않을까요?

2022-10-11 23:52 UTC, junyng commented on AppPackage/Sources/Calendar/Day.swift
> +    public var isWithinDisplayedMonth: Bool
Day가 현재 월에 포함되었는지 여부를 판단하는것처럼 보이는 프로퍼티네요

현재 월에 이전달의 정보를 가지고 있는게 조금 어색할 수 있을것 같다고 들어요

제 생각이지만 [Month: [Day]] 라는 딕셔너리가 있다면
예를 들어 8월에서 보여지지 않아야할 7월 마지막의 Day 배열을 구한다면 
(count = 8월의 시작일 weekDay-1) 만큼의 값을 이전달 7월의 Day Array.suffix(count) 만큼 가져오면 위에 선언하신 프로퍼티 없이 구현을 할 수 있지않을까 의견을 남겨봅니다

2022-10-13 16:00 UTC, GangWoon commented
주말에 아래 그림에 대해서 의논하는 시간을 갖을 수 있다면 좋을 거 같습니다.
달력을 원하는대로 그리기 위해서 제가 생각한 방법은 아래와 같습니다.
전체 데이터를 관리할 source와 뷰에서 보여질 데이터를 각각 따로 관리하게 되면서, 뷰에서 보여지는 데이터가 변경됐을 떄, 소스까지 변경이 되도록 싱크를 맞춰야 했습니다.

최종적으로 저희 앱 특성상 세로 방향으로 캘린더가 갱신되는게 아닌, 가로로 캘린더가 갱신되기 때문에 중복 데이터를 갖을 수 밖에 없는 구조입니다. 이는 결국 이차원 배열로 관리가 되어야 합니다. 

캘린더 뷰의 경우 DayState로 표기한 값이 구조체가 아닌 클래스일 때 이득을 볼 거 같은 상황이라고 판단했습니다.
상태를 구현할 때, 문제가 되지 않는지 체크해보도록 하겠습니다.

![Untitled-2022-10-01-1850](https://user-images.githubusercontent.com/48466830/195638993-4d304d9a-3490-414e-8301-8500426f4f30.png)
![Untitled-2022-10-01-1850-2](https://user-images.githubusercontent.com/48466830/195639015-0e7114ce-7fb1-459f-a524-07af3540b95f.png)

2023-01-29 01:18 UTC, GangWoon commented
데이터를 다루는 부분을 전적으로 수정했습니다. 월에 대한 데이터를 따로 두고 뷰에서 보여질 데이터를 새로 생성하는게 아닌 서로 연관 없는 데이터를 생성해서 처리하도록 수정했습니다. 이렇게 됐을때 타겟 월을 기준으로 다른 월로 이동시에 데이터를 수정하도록 구현하려고 합니다. 
추후 실제 코드를 작성할 때 따로 코맨트 드리도록 하겠습니다.

해당 PR은 머지 후 바로 뷰 작업을 진행하도록 하겠습니다 :)
<img width="536" alt="Screenshot 2023-01-29 at 10 16 18" src="https://user-images.githubusercontent.com/48466830/215298689-41727c55-ddc6-4182-bf4f-39cd0122f6b7.png">

2023-02-04 06:18 UTC, junyng approved these changes

2023-02-04 06:42 UTC, merged