[PI-17] 공통으로 사용할 화면을 모듈로 분리
Team-Planz/Planz-iOS pull request #41
Opened 2023-03-27 02:59 UTC by Jinsujin

## ISSUE
- resolved #{issue_number}

<br>

## 작업 내용
- [x] 공통화면 모듈인 CommomView 생성
- [x] 약속 상세 화면 분리
- [x] 에러 화면 분리
- [x] 데이터가 없어요 화면 분리

<br>

## Check List
- [ ] PR 제목은 `[ISSUE-{N}] PR 제목`으로 작성
- [ ] CI/CD 통과 여부
- [ ] 1명 이상의 Approve 확인 후 Merge
- [ ] 관련 이슈 연결

2023-03-28 07:29 UTC, GangWoon requested changes
파일 체인지에 디프가 적절하게 잡히지 않아서 글로 코맨트를 남깁니다.
1. 이미지 에셋을 pdf파일로 변경해주실 수 있을까요? 싱글 스케일 설정까지 부탁드리겠습니다 :)
2.  EmptyDataView 약속잡기 버튼 엑션을 만들어 주실 수 있을까요? EmptyDataView 내부에서 처리하기 위해서 만드는게 아닌, 추후 상위 뷰에서 엑션을 잡을 수 있게 준비하면 좋을 거 같습니다.
3. PromiseDetailView에 NavigationView를 추가하신 이유는 무엇일까요?

2023-03-29 08:37 UTC, Jinsujin commented
수정한 작업본 push 했습니다!
@GangWoon 이미지를 png 가 아닌, pdf 로 관리하면 어떤 이점이 있나요?

2023-03-29 09:01 UTC, GangWoon commented on AppPackage/Sources/PromiseManagement/Standby/StandbyListView.swift
> +                Text("Empty")
EmptyView를 누락시킨거 같습니다.

2023-03-29 12:02 UTC, Jinsujin commented
@GangWoon 벡터의 이점을 살리기 위해서 PDF 를 쓰는걸로 이해했습니다! PDF 대신 같은 벡터형식인 svg 파일 형식은 어떤가요?
pdf(Portable Document Format) 는 문서라는 느낌이고 svg(Scalable Vector Graphics) 쪽이 이미지 리소스 쪽인 느낌인것 같습니다.

24*24 사이즈의 이미지(+ 아이콘)를 변환했을때 파일 사이즈를 비교해봤어요:
- PNG: 1x(225byte), 2x(357byte), 3x(473byte) = 약 1000byte
- svg: 854 byte
- pdf: 1874 byte

아이콘 같이 단순한 이미지인 경우에는 svg 쪽이 우세한듯 합니다!
아래 글을 살펴보니 그라데이션이 있는 이미지일 경우, 벡터형식으로 변환하면 안나오는 경우가 있다고 하니 적용후에도 확인이 필요할듯 해요~!

[글: svg 와 png 비교](https://medium.com/delightroom/ios-%EC%84%B8%EA%B3%84-1%EC%9C%84-%EC%95%8C%EB%9E%8C-%EC%95%B1%EC%97%90%EC%84%9C-image-asset%EC%9D%84-%EA%B4%80%EB%A6%AC%ED%95%98%EB%8A%94-%EB%B2%95-png-vs-svg-a0291029b233)

2023-03-29 12:05 UTC, Jinsujin commented on AppPackage/Sources/PromiseManagement/Standby/StandbyListView.swift
> +                Text("Empty")
앗 수정하겠습니다!

2023-03-30 04:53 UTC, GangWoon commented
말씀하신대로 벡터의 이점을 살리기 위해선 svg로 통일하는게 좋을 듯 합니다. 추후 작업으로 이미지 에셋 전부 수정하도록 하는 방향으로 가겠습니다.
:) 친절한 정리 감사합니다.

2023-03-30 04:54 UTC, GangWoon approved these changes

2023-03-30 06:59 UTC, Jinsujin commented
저도 이후에 올리는 이미지들 svg 로 올리도록 할께요!

2023-03-30 12:27 UTC, merged